### ISSUE TITLE
This repo does not provide pecl - and neither does anything else I can find

### ISSUE THREAD

**Issue by edgreenberg** [davidalger/php74-pecl-zip#2]
There is nothing but a spec file.  I have installed all the IUS PHP74 stuff, but no pear, no pecl. (Also no mcrypt)  Am I missing something?

**Comment by jeffsheltren** [comment]
Hi, you filed this in the `php74-pecl-zip` issue queue, so I'm not clear exactly which PECL extension you're looking for? The IUS git repos contain the spec files used to build packages, which are then copied out to the repo.

Regarding mcrypt, that's been deprecated and removed from core PHP: https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt -- see also https://stackoverflow.com/questions/41272257/mcrypt-is-deprecated-what-is-the-alternative

I'm going to close this out as it doesn't seem related to php74-pecl-zip. If you have a specific request, you can open an issue in the `wishlist` queue.

**Comment by edgreenberg** [comment]
So are you telling me that if I use the IUS repo I have no way of getting
mcrypt back to handle my legacy databases filled with encrypted data?
